import { Stall, MenuItem, PreOrderSlot, User, Order } from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-student-1',
    name: 'Ahmad Rizky Pratama',
    email: 'ahmad@sekolah.sch.id',
    role: 'STUDENT',
    nisn: '20240101',
    balance: 75000,
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'user-student-2',
    name: 'Siti Nurhaliza',
    email: 'siti@sekolah.sch.id',
    role: 'STUDENT',
    nisn: '20240102',
    balance: 50000,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'user-seller-1',
    name: 'Ibu Siti Rahayu',
    email: 'admin_siti@kantin.sch.id',
    role: 'SELLER',
    balance: 1450000,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'user-seller-2',
    name: 'Pak Joko Widodo',
    email: 'admin_joko@kantin.sch.id',
    role: 'SELLER',
    balance: 980000,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
];

export const INITIAL_STALLS: Stall[] = [
  {
    id: 'stan-1',
    name: 'Stan 01 - Dapur Bu Siti',
    description: 'Spesialis hidangan nasi nusantara, ayam geprek krispi, dan olahan ayam gurih lezat.',
    sellerId: 'user-seller-1',
    category: 'Aneka Nasi & Ayam',
    rating: 4.9,
    openTime: '07:00 - 15:30 WIB',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'stan-2',
    name: 'Stan 02 - Bakso & Mie Nusantara Pak Joko',
    description: 'Bakso sapi asli dengan kuah kaldu sapi gurih segar, mie ayam pangsit, dan aneka mie pedas.',
    sellerId: 'user-seller-2',
    category: 'Bakso & Mie Kuah',
    rating: 4.8,
    openTime: '07:30 - 15:00 WIB',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'stan-3',
    name: 'Stan 03 - Minuman Segar & Boba Kak Dina',
    description: 'Pelepas dahaga istirahat: Es Teh Manis Solo, Boba Brown Sugar, Matcha Latte & Jus Segar.',
    sellerId: 'user-seller-1',
    category: 'Minuman Dingin & Boba',
    rating: 4.9,
    openTime: '07:00 - 15:30 WIB',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'stan-4',
    name: 'Stan 04 - Snack Corner & Pastry',
    description: 'Aneka cemilan hangat, Risol Mayo lumer, Dimsum Mentai, Roti Bakar Coklat Keju & Donat.',
    sellerId: 'user-seller-2',
    category: 'Cemilan & Bakery',
    rating: 4.7,
    openTime: '07:00 - 15:00 WIB',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
  },
];

export const INITIAL_MENUS: MenuItem[] = [
  // Stan 1
  {
    id: 'menu-101',
    stallId: 'stan-1',
    name: 'Paket Ayam Geprek Sambal Bawang + Nasi',
    category: 'makanan',
    price: 15000,
    originalPrice: 17000,
    isAvailable: true,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
    description: 'Ayam krispi digeprek dengan sambal bawang segar khas Bu Siti, nasi pulen hangat & timun.',
  },
  {
    id: 'menu-102',
    stallId: 'stan-1',
    name: 'Nasi Goreng Spesial Telur Ceplok',
    category: 'makanan',
    price: 13000,
    originalPrice: 13000,
    isAvailable: true,
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    description: 'Nasi goreng harum bumbu rempah otentik, suwiran ayam, sosis, telur ceplok dan kerupuk.',
  },
  {
    id: 'menu-103',
    stallId: 'stan-1',
    name: 'Nasi Kuning Komplit Telur Balado',
    category: 'makanan',
    price: 12000,
    originalPrice: 12000,
    isAvailable: true,
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    description: 'Nasi kuning wangi santan & kunyit asli, orek tempe manis, bihun goreng, serundeng, telur balado.',
  },
  {
    id: 'menu-104',
    stallId: 'stan-1',
    name: 'Ayam Bakar Madu Pedas Manis',
    category: 'makanan',
    price: 16000,
    originalPrice: 18000,
    isAvailable: false, // Out of stock demo
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
    description: 'Potongan ayam dibakar dengan bumbu madu gurih manis khas meresap hingga ke tulang. (Stok Habis)',
  },

  // Stan 2
  {
    id: 'menu-201',
    stallId: 'stan-2',
    name: 'Bakso Sapi Urat Komplit',
    category: 'makanan',
    price: 15000,
    originalPrice: 15000,
    isAvailable: true,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    description: 'Bakso urat besar, 3 bakso halus, tahu bakso, mie kuning, bihun, kuah kaldu sapi asli gurih.',
  },
  {
    id: 'menu-202',
    stallId: 'stan-2',
    name: 'Mie Ayam Pangsit Komplit',
    category: 'makanan',
    price: 14000,
    originalPrice: 14000,
    isAvailable: true,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80',
    description: 'Mie kenyal gurih topping ayam kecap manis gurih, caisim, pangsit rebus lembut & pangsit goreng.',
  },
  {
    id: 'menu-203',
    stallId: 'stan-2',
    name: 'Mie Pedas Level 3 (Mie Jebew)',
    category: 'makanan',
    price: 12000,
    originalPrice: 12000,
    isAvailable: true,
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
    description: 'Mie pedas bumbu cabai rawit melimpah, ayam cincang, daun bawang, dan kerupuk pangsit.',
  },
  {
    id: 'menu-204',
    stallId: 'stan-2',
    name: 'Bakso Cuanki Super Pedas',
    category: 'makanan',
    price: 13000,
    originalPrice: 13000,
    isAvailable: false, // Out of stock demo
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80',
    description: 'Cuanki lidah, tahu bakso, siomay kering, dan kuah jeruk limau cabai pedas. (Stok Habis)',
  },

  // Stan 3
  {
    id: 'menu-301',
    stallId: 'stan-3',
    name: 'Es Teh Manis Solo Jumbo',
    category: 'minuman',
    price: 4000,
    originalPrice: 4000,
    isAvailable: true,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
    description: 'Es teh wangi khas racikan tubruk Solo dengan rasa manis pas porsi jumbo 500ml.',
  },
  {
    id: 'menu-302',
    stallId: 'stan-3',
    name: 'Brown Sugar Fresh Milk Boba',
    category: 'minuman',
    price: 10000,
    originalPrice: 12000,
    isAvailable: true,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1558857563-b37cfbbf276b?auto=format&fit=crop&w=600&q=80',
    description: 'Susu segar dingin berpadu sirup gula aren legit dan boba tapioka kenyal empuk.',
  },
  {
    id: 'menu-303',
    stallId: 'stan-3',
    name: 'Matcha Green Tea Creamy Ice',
    category: 'minuman',
    price: 9000,
    originalPrice: 9000,
    isAvailable: true,
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    description: 'Minuman matcha asli berpadu susu creamy yang wangi dan menyegarkan.',
  },
  {
    id: 'menu-304',
    stallId: 'stan-3',
    name: 'Jus Alpukat Kocok Cokelat',
    category: 'minuman',
    price: 10000,
    originalPrice: 12000,
    isAvailable: true,
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1622597467836-f3e6e75bc037?auto=format&fit=crop&w=600&q=80',
    description: 'Alpukat mentega matang dikocok kental manis cokelat dan es serut segar.',
  },

  // Stan 4
  {
    id: 'menu-401',
    stallId: 'stan-4',
    name: 'Risol Mayo Smoked Beef & Telur (Isi 2)',
    category: 'snack',
    price: 8000,
    originalPrice: 8000,
    isAvailable: true,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&w=600&q=80',
    description: 'Kulit risol renyah tepung panir dengan isian daging asap gurih, telur, mayones lumer.',
  },
  {
    id: 'menu-402',
    stallId: 'stan-4',
    name: 'Dimsum Ayam Mentai Mozzarella (Isi 4)',
    category: 'snack',
    price: 12000,
    originalPrice: 14000,
    isAvailable: true,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=600&q=80',
    description: 'Dimsum ayam juicy lembut saus mentai gurih khas jepang dibakar keju mozzarella.',
  },
  {
    id: 'menu-403',
    stallId: 'stan-4',
    name: 'Roti Bakar Cokelat Keju Double',
    category: 'snack',
    price: 10000,
    originalPrice: 10000,
    isAvailable: true,
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=600&q=80',
    description: 'Roti tebal dipanggang margarin wangi dengan coklat meises melimpah dan taburan keju cheddar.',
  },
];

export const PREORDER_SLOTS: PreOrderSlot[] = [
  {
    id: 'slot-1',
    name: 'Jam Istirahat 1',
    time: '09:30 - 10:00 WIB',
    badge: 'Paling Populer',
    desc: 'Pesanan Kamu siap hangat tepat saat bel istirahat pertama berbunyi.',
  },
  {
    id: 'slot-2',
    name: 'Jam Istirahat 2 (Makan Siang)',
    time: '12:00 - 12:45 WIB',
    badge: 'Makan Siang',
    desc: 'Ambil makan siang tanpa harus antre berdesakan di kantin.',
  },
  {
    id: 'slot-3',
    name: 'Jam Pulang Sekolah',
    time: '15:00 - 15:30 WIB',
    badge: 'Sore / Ekskul',
    desc: 'Cemilan dan minuman siap santap sebelum pulang atau latihan ekskul.',
  },
  {
    id: 'slot-custom',
    name: 'Waktu Kustom / Spesifik',
    time: 'Pilih Jam Sendiri',
    badge: 'Fleksibel',
    desc: 'Tentukan jam menit pengambilan khusus sesuai jadwal kelas Kamu.',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderCode: 'ORD-8492',
    userId: 'user-student-1',
    userName: 'Ahmad Rizky Pratama',
    userNisn: '20240101',
    stallId: 'stan-1',
    stallName: 'Stan 01 - Dapur Bu Siti',
    totalPrice: 19000,
    discount: 0,
    isPreOrder: true,
    pickupTime: 'Jam Istirahat 1 (09:30 - 10:00 WIB)',
    paymentMethod: 'Kartu Pelajar Digital (E-Money)',
    status: 'READY',
    notes: 'Sambal sedang, es batu sedikit.',
    createdAt: new Date().toISOString(),
    items: [
      { menuItemId: 'menu-101', name: 'Paket Ayam Geprek Sambal Bawang + Nasi', price: 15000, quantity: 1 },
      { menuItemId: 'menu-301', name: 'Es Teh Manis Solo Jumbo', price: 4000, quantity: 1 },
    ],
  },
  {
    id: 'ord-2',
    orderCode: 'ORD-7731',
    userId: 'user-student-2',
    userName: 'Siti Nurhaliza',
    userNisn: '20240102',
    stallId: 'stan-2',
    stallName: 'Stan 02 - Bakso & Mie Nusantara Pak Joko',
    totalPrice: 15000,
    discount: 0,
    isPreOrder: false,
    pickupTime: 'Pesan Langsung (Sekarang)',
    paymentMethod: 'QRIS Kantin Digital',
    status: 'COOKING',
    notes: 'Kuah banyakin, seledri pisah.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    items: [
      { menuItemId: 'menu-201', name: 'Bakso Sapi Urat Komplit', price: 15000, quantity: 1 },
    ],
  },
];
